### ISSUE TITLE
Outgoing messages not being sent

### ISSUE THREAD

**Issue by tfreedman** [matrix-hacks/matrix-puppet-skype#3]
{ poll: An error happened while processing the polled messages
  caused by Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TLSWrap.onread (net.js:568:26)
  name: 'poll',
  [_message]: 'An error happened while processing the polled messages',
  data: {},
  cause: 
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1018:11)
       at TLSWrap.onread (net.js:568:26)
     [stack]: [Getter/Setter],
     [message]: 'read ECONNRESET',
     code: 'ECONNRESET',
     errno: 'ECONNRESET',
     syscall: 'read' },
  [_stack]: 'poll: An error happened while processing the polled messages\n  caused by Error: read ECONNRESET\n    at exports._errnoException (util.js:1018:11)\n    at TLSWrap.onread (net.js:568:26)',
  [_stackContainer]: undefined,
  message: 'poll: An error happened while processing the polled messages\n  caused by Error: read ECONNRESET\n    at exports._errnoException (util.js:1018:11)\n    at TLSWrap.onread (net.js:568:26)' }

I can receive messages people send me over Skype, but I can't send outgoing messages from within Matrix.

**Comment by kfatehi** [comment]
@tfreedman Did you ever figure this out? Works on my end.

**Comment by Sorunome** [comment]
Since this error is within skype-http itself and as of recently the version got bumped, perhaps it is fixed?

**Comment by tfreedman** [comment]
I just came back to playing around with this, and I still have the same issue (but with different symptoms). Messages that I send and receive from within Skype show up in Matrix, but anything typed into Matrix doesn't get sent to Skype.

Console output for three messages typed in Riot just shows:

$ tail -f /var/log/matrix-skype.log:
Receive a read event from ourself
Receive a read event from ourself
Receive a read event from ourself

**Comment by Sorunome** [comment]
Can you CURL into the puppet? Did you try this fix? https://github.com/matrix-org/synapse/issues/1834 As it might be a synapse bug

**Comment by tfreedman** [comment]
Do you have specific commands I can try running? I'm not too familiar with the matrix sqlite db, so I'd prefer to not just poke it blindly.

**Comment by tfreedman** [comment]
Alternatively, would re-registering the appservice fix this, and prevent the need for poking around in the DB?

**Comment by tfreedman** [comment]
So I just re-generated my config file and restarted my home server, and the problem appears to be solved.
